services:
  # apt cache server
  apt-cache:
    build:
      context: apt-cache
    container_name: apt-cache
    restart: unless-stopped
    ports:
      # - 127.0.0.1:3142:3142
      - 3142:3142
    volumes:
      - ./apt-cache/cache:/var/cache/apt-cacher-ng
    networks:
      - nextlabs

  # pypi (python) cache server
  pypiserver:
    image: pypiserver/pypiserver:latest
    container_name: pypi-cache
    ports:
      - "8080:8080"
    volumes:
      - ./pypi-cache:/data/packages
    networks:
      - nextlabs

  # npmjs cache
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'npmjs-cache'
    networks:
      - nextlabs
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio/storage:/verdaccio/storage'
      - './verdaccio/config:/verdaccio/conf'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net

  # docker metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    command:
      - '-port=9092'
      - '-housekeeping_interval=10s'
    expose:
      - 9092
    networks:
      - monitor-net

  # time series database
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    networks:
      - monitor-net

  # system metrics
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net

  caddy:
    image: caddy:2.7.6
    container_name: caddy
    ports:
      - "3000:3000"
      - "9092:9092"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./monitoring/caddy:/etc/caddy
    restart: unless-stopped
    networks:
      - monitor-net

networks:
  nextlabs:
    external: true
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
