{
 "title": "Docker and Host Monitoring w/ Prometheus",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(count(container_last_seen{job=\"cadvisor\", name!=\"\"}))"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}