version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=tajnyheslo
      - MYSQL_DATABASE=Pizzerie
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    container_name: databaze
    restart: always
    ports:
      - 8306:3306
    volumes:
      - ./pizzerie.sql:/docker-entrypoint-initdb.d/pizzerie.sql
    networks:
      - databaze
    
networks:
  databaze:

# mysql -h 127.0.0.1 -P 8306 -u root -ptajnyheslo